### PR TITLE
Add Portuguese translation

### PR DESCRIPTION
**Pull request by mill1000**
Thanks to @pdtgit

### CODE REVIEW

**Comment by mill1000** [comment]
@pdtgit Have you had a chance to review these? Any changes you want to make?

**Comment by mill1000** [comment]
Going to merge this and make a release. Create a new PR if any changes are needed.

**Comment by pdtgit** [comment]
> @pdtgit Have you had a chance to review these? Any changes you want to make?

Hi! Sorry for the late reply... I would say the translation is good enough, I actually use it in English so wasn't able to correct any misunderstood error.

**Comment by mill1000** [comment]
No worries. Thanks again for the translation

**Pull request merged**
