### PR TITLE
Intelligently populate fan speed options and add support for custom fan speeds

### LINKED ISSUE #40: Intelligently populate fan speed options
When https://github.com/mill1000/midea-msmart/issues/83 is implemented the HA integration should intelligently display available fan speed.

### PR DESCRIPTION
**Pull request by mill1000**
Use device capabilities to intelligently populate available fan speeds. On devices that support it, add a custom fan speed control via a number entity.

Also, reduce de-bounce on coordinator to make number and climate response better.

Close #40

### CODE REVIEW

**Comment by franzenel** [comment]
When I go to Fan to set Auto, low, med...  It is just black.  I can control the speed by using Node-red but in the cards they are missing.  I have options for all other settings, just not the fan speed. I have 4 head units and they are all acting this way.

**Comment by mill1000** [comment]
Yes this has been reported in https://github.com/mill1000/midea-msmart/issues/88, and I've got a fix lined up in https://github.com/mill1000/midea-msmart/pull/90

You can test the fix if you'd like by installing the branch with pip as shown here:
https://github.com/mill1000/midea-msmart/issues/88#issuecomment-1783179709

**Comment by franzenel** [comment]
I will try that. Thanks.

**Comment by franzenel** [comment]
I am running this on a Pi 4 can I install it using PIP.  never done that before.

**Comment by mill1000** [comment]
Yes, but you'll need to execute it within the proper environment. 

If you're using HAOS, you'll need to get inside the Docker container that runs HA. This add-on will allow you to do that: https://github.com/hassio-addons/addon-ssh

**Comment by franzenel** [comment]
I uninstalled the HACS version and ran the install from the terminal
image
but now I get a message saying Media is missing.

**Comment by mill1000** [comment]
Keep the integration installed via HACs. You only need to update the underlying library `.msmart-ng`

1. Reinstall via HACs.
2. Restart HA, ensure devices are there.
3. Get a terminal into the docker container running HA. This **isn't** the same as just getting into a terminal on HAOS.
  1. Some help here: https://community.home-assistant.io/t/howto-how-to-access-the-home-assistant-os-host-itself-over-ssh/263352/5
  2. Run `docker ps` and look for the HA container. Might be called hass or homeassistant
  3. Run  `docker exec <containername> -it bash`
4. Run the pip command.

Or you could wait for me to merge this fix and make a release, but it would be nice to have confirmation that the fix works for you.

**Pull request merged**
